version: '3.1'

services:
  nexus:
    container_name: lde-nexus
    image: "sonatype/nexus3"
    restart: always
    networks:
      - env-network
    ports:
      - 8887:8081
    volumes:
      - nexus-data:/nexus-data:z
  dind:
    container_name: lde-dind
    image: "docker:dind"
    privileged: true
    restart: always
    networks:
      env-network:
        aliases:
          - docker
    ports:
      - 2376:2376
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home:z
      - jenkins-agent:/home/jenkins:z
      - jenkins-docker-certs:/certs/client:z
    environment:
      - DOCKER_TLS_CERTDIR=/certs
  jenkins:
    container_name: lde-jenkins
    build:
      context: ./blueocean
      args:
        - ks_pass=${KEY_STORE_PASS}
    depends_on:
      - dind
      - agent
    restart: always
    networks:
      - env-network
    ports:
      - 8888:8083
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home:z
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - DOCKER_HOST=tcp://docker:2376
    extra_hosts:
      - "host.docker.internal:host-gateway"
  agent:
    container_name: lde-agent
    build:
      context: ./agent
    depends_on:
      - dind
    tty: true
    volumes:
      - jenkins-agent:/home/jenkins
      - jenkins-docker-certs:/certs/client:ro
      - ./agent/ssh-conf:/home/jenkins/.ssh
    networks:
      - env-network
    env_file:
      - ./agent/agent.env
    environment:
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - DOCKER_HOST=tcp://docker:2376
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  env-network:
    name: lde-net

volumes:
  nexus-data:
  jenkins-data:
  jenkins-docker-certs:
  jenkins-agent: