version: '3.1'

services:
  nexus:
    container_name: lde-nexus
    image: "sonatype/nexus3"
    restart: always
    networks:
      - env-network
    ports:
      - 8887:8081
    volumes:
      - nexus-data:/nexus-data
  jenkins:
    container_name: lde-jenkins
    build:
      context: jenkins
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    restart: always
    networks:
      - env-network
    ports:
      - 8888:8080
      - 50000:50000
    tty: true
    volumes:
      - ${HOST_DOCKER}:/var/run/docker.sock
      - ${HOST_JENKINS_DATA}:/var/jenkins_home
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  env-network:
    name: lde-net

volumes:
  nexus-data: