#!/usr/bin/env bash
if [ -n "$HOSTS_TO_CHECK" ]; then
  IFS="," read -r -a itemsArray <<< "$HOSTS_TO_CHECK"
  for item in "${itemsArray[@]}"; do
    IFS=":" read -r -a parts <<< "$item"
    host=${parts[0]}
    port=${parts[1]}
    echo "KEYSCAN HOST: ${host}; PORT: ${port}"
    ssh-keyscan -H -p "$port" "$host" >> "${JENKINS_AGENT_HOME}/.ssh/known_hosts"
  done
fi
setup-sshd